# -*- coding: utf-8 -*-
"""subset selection problem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kzTxR8dyrF5dycXBPH7dFkY_ABiq2fi-

Subset Selection Problem
1. Problem Statement:
Find all the subsets from a set of numbers whose sum is zero.

Constraint: Subset size must be 5
Set={-12, -3, -6, 7, 2, -2, 6, 3, 9, -7, -5, -8, 1, 11, -9, -4}

1.1 Library inclusion
"""

import random as r

"""1.2 Parameter Setting"""

Set         = set([-12, -3, -6, 7, 2, -2, 6, 3, 9, -7, -5, -8, 1, 11, -9, -4])
SetSize     = 5
ResultList  = set()    # Store Result List i.e. list of sets whose sum is zero
Iterations  = 1000    # Number of Inerations

"""1.3 Start Program"""

Set         = set([-12, -3, -6, 7, 2, -2, 6, 3, 9, -7, -5, -8, 1, 11, -9, -4])
SetSize     = 5
ResultList  = set()    # Store Result List i.e. list of sets whose sum is zero
Iterations  = 1000    # Number of Inerations
for i in range(Iterations):
    # Select number of elements from Set
    Chromosome = r.sample(list(Set),SetSize) # Convert Set to list before sampling
    if sum(Chromosome) == 0:
        ResultList.add(tuple(sorted(Chromosome)))

"""1.4 Print the sets and total count"""

# Print all the sets whose sum is zero
for r in ResultList:
	print (r)

# Print total sets
print ("\nTotal Sets: ", len(ResultList), "\n")

"""1.5 Complete Program"""

#-------------------------------------------------------------
# Step 1: Library inclusion
#-------------------------------------------------------------
import random as r


#-------------------------------------------------------------
# Step 2: Parameter Setting
#-------------------------------------------------------------
Set         = set([-12, -3, -6, 7, 2, -2, 6, 3, 9, -7, -5, -8, 1, 11, -9, -4])
SetSize     = 5
ResultList  = set()    # Store Result List i.e. list of sets whose sum is zero
Iterations  = 1000   # Number of Inerations


#-------------------------------------------------------------
# Step3: Start Program
#-------------------------------------------------------------

# Loop till number of Iterations
for i in range(Iterations):
    # Select number of elements from Set
    Chromosome = r.sample(list(Set),SetSize) # Convert Set to list before sampling

    # Sum the number of elements in the Chromosome
    if sum(Chromosome) == 0:
        ResultList.add(tuple(sorted(Chromosome))) # Sort the Chromosome before adding to ResultList to ensure uniqueness

# Print all the sets whose sum is zero
for r in ResultList:
        print (r)

# Print total sets
print ("\nTotal Sets: ", len(ResultList))

"""1.6 Complete Program with sorting"""

#-------------------------------------------------------------
# Step 1: Library inclusion
#-------------------------------------------------------------
import random as r


#-------------------------------------------------------------
# Step 2: Parameter Setting
#-------------------------------------------------------------
Set         = set([-12, -3, -6, 7, 2, -2, 6, 3, 9, -7, -5, -8, 1, 11, -9, -4])
SetSize     = 5
ResultList  = set()    # Store Result List i.e. list of sets whose sum is zero
Iterations  = 1000   # Number of Inerations


#-------------------------------------------------------------
# Step3: Start Program
#-------------------------------------------------------------

# Loop till number of Iterations
for i in range(Iterations):
    # Select number of elements from Set
    Chromosome = r.sample(list(Set),SetSize) # Convert Set to list before sampling
    Chromosome.sort()

    # Sum the number of elements in the Chromosome
    if sum(Chromosome) == 0:
        ResultList.add(tuple(sorted(Chromosome)))

# Print all the sets whose sum is zero
for r in ResultList:
        print (r)

# Print total sets
print ("\nTotal Sets: ", len(ResultList))

"""2. Problem Statement:
Find all the subsets from a set of numbers whose sum is zero.

Constraint: Subset size must be 3 to 6 only
Set={-12, -3, -6, 7, 2, -2, 6, 3, 9, -7, -5, -8, 1, 11, -9, -4}
"""

#-------------------------------------------------------------
# Step 1: Library inclusion
#-------------------------------------------------------------
import random as r


#-------------------------------------------------------------
# Step 2: Parameter Setting
#-------------------------------------------------------------
Set         = set([-12, -3, -6, 7, 2, -2, 6, 3, 9, -7, -5, -8, 1, 11, -9, -4])
SetLB       = 3
SetUB       = 6
ResultList  = set()    # Store Result List i.e. list of sets whose sum is zero
Iterations  = 1000   # Number of Inerations


#-------------------------------------------------------------
# Step3: Start Program
#-------------------------------------------------------------

# Loop till number of Iterations
for i in range(Iterations):
    # Select set size randomly
    SetSize = r.randint(SetLB,SetUB)

    # Select number of elements from Set
    Chromosome = r.sample(list(Set),SetSize) # Convert Set to list before sampling
    Chromosome.sort()

    # Sum the number of elements in the Chromosome
    if sum(Chromosome) == 0:
        ResultList.add(tuple(sorted(Chromosome)))

# Print all the sets whose sum is zero
for r in ResultList:
        print (r)

# Print total sets
print ("\nTotal Sets: ", len(ResultList))